version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mdmgg

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 60
      runas: root
    - location: scripts/health_check.sh
      timeout: 60
      runas: root
    - location: scripts/switch.sh
      timeout: 60
      runas: root